/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : string,
  'dayOfWeek' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderType' : OrderType,
  'totalAmount' : number,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'estimatedTime' : bigint,
}
export interface OrderItem { 'itemId' : string, 'quantity' : bigint }
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type OrderType = { 'dineIn' : null } |
  { 'takeaway' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'online' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface Rating {
  'itemId' : string,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'addRating' : ActorMethod<[Rating], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAverageRating' : ActorMethod<[string], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuByDay' : ActorMethod<[string], Array<MenuItem>>,
  'getMenuItem' : ActorMethod<[string], [] | [MenuItem]>,
  'getMenuItemCount' : ActorMethod<[], bigint>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByDate' : ActorMethod<[Time], Array<Order>>,
  'getOrdersByDateRange' : ActorMethod<[Time, Time], Array<Order>>,
  'getQueueOrders' : ActorMethod<[], Array<Order>>,
  'getRatingsForItem' : ActorMethod<[string], Array<Rating>>,
  'getSalesSummary' : ActorMethod<
    [Time],
    { 'totalOrders' : bigint, 'totalRevenue' : number }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderAsDelivered' : ActorMethod<[string], undefined>,
  'markPaymentAsPaid' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, OrderType, PaymentMethod, string],
    string
  >,
  'removeMenuItem' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedMenuItems' : ActorMethod<[Array<MenuItem>], undefined>,
  'updateEstimatedTime' : ActorMethod<[string, bigint], undefined>,
  'updateMenuItem' : ActorMethod<[string, MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];