/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const Rating = IDL.Record({
  'itemId' : IDL.Text,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'online' : IDL.Null,
});
export const OrderType = IDL.Variant({
  'dineIn' : IDL.Null,
  'takeaway' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'itemId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'orderType' : OrderType,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
  'estimatedTime' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'addRating' : IDL.Func([Rating], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuByDay' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByDate' : IDL.Func([Time], [IDL.Vec(Order)], ['query']),
  'getOrdersByDateRange' : IDL.Func([Time, Time], [IDL.Vec(Order)], ['query']),
  'getQueueOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRatingsForItem' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
  'getSalesSummary' : IDL.Func(
      [Time],
      [IDL.Record({ 'totalOrders' : IDL.Nat, 'totalRevenue' : IDL.Float64 })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
  'markPaymentAsPaid' : IDL.Func([IDL.Text], [], []),
  'nextDay' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), OrderType, PaymentMethod, IDL.Text],
      [IDL.Text],
      [],
    ),
  'removeMenuItem' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEstimatedTime' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Rating = IDL.Record({
    'itemId' : IDL.Text,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cash' : IDL.Null, 'online' : IDL.Null });
  const OrderType = IDL.Variant({ 'dineIn' : IDL.Null, 'takeaway' : IDL.Null });
  const OrderItem = IDL.Record({ 'itemId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'orderType' : OrderType,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
    'estimatedTime' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'addRating' : IDL.Func([Rating], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuByDay' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByDate' : IDL.Func([Time], [IDL.Vec(Order)], ['query']),
    'getOrdersByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getQueueOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRatingsForItem' : IDL.Func([IDL.Text], [IDL.Vec(Rating)], ['query']),
    'getSalesSummary' : IDL.Func(
        [Time],
        [IDL.Record({ 'totalOrders' : IDL.Nat, 'totalRevenue' : IDL.Float64 })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOrderAsDelivered' : IDL.Func([IDL.Text], [], []),
    'markPaymentAsPaid' : IDL.Func([IDL.Text], [], []),
    'nextDay' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), OrderType, PaymentMethod, IDL.Text],
        [IDL.Text],
        [],
      ),
    'removeMenuItem' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEstimatedTime' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };